"""Populate the database with test data.

Usage:
    python seed.py

Creates 5 users, 10 projects, 500+ flashcards with varied
difficulty, and study session history.
"""

import sqlite3
import random
from werkzeug.security import generate_password_hash

DB_PATH = "database.db"

USERS = [
    ("alice", "password123"),
    ("bob", "password123"),
    ("carol", "password123"),
    ("dave", "password123"),
    ("eve", "password123"),
]

PROJECTS = [
    (1, "Python Basics", 1),
    (1, "Flask Web Development", 0),
    (1, "SQL Fundamentals", 1),
    (2, "JavaScript Essentials", 1),
    (2, "Data Structures", 0),
    (3, "World Capitals", 1),
    (3, "Spanish Vocabulary", 1),
    (4, "Biology 101", 0),
    (4, "Chemistry Basics", 1),
    (5, "History Dates", 0),
]

CARD_SETS = {
    "Python Basics": [
        ("What keyword defines a function?", "def"),
        ("How do you start a comment?", "# character"),
        ("What is a list comprehension?",
         "A concise way to create lists: [x for x in range(10)]"),
        ("What does len() do?", "Returns the length of an object"),
        ("How do you create a dictionary?",
         "Using curly braces: {'key': 'value'}"),
        ("What is a tuple?", "An immutable ordered sequence"),
        ("What does 'self' refer to?",
         "The current instance of a class"),
        ("What is PEP 8?", "Python style guide"),
        ("How do you handle exceptions?",
         "Using try/except blocks"),
        ("What is a lambda function?",
         "An anonymous inline function"),
        ("What does import do?", "Loads a module"),
        ("What is None?", "Python's null value"),
        ("How do you slice a list?",
         "Using [start:stop:step] syntax"),
        ("What is __init__?",
         "Constructor method for a class"),
        ("What does range() return?",
         "A sequence of numbers"),
        ("What is a generator?",
         "A function that yields values lazily"),
        ("How do you read a file?",
         "Using open() and read() or with statement"),
        ("What is a decorator?",
         "A function that wraps another function"),
        ("What does strip() do?",
         "Removes leading and trailing whitespace"),
        ("What is pip?", "Python package installer"),
        ("What is a set in Python?",
         "An unordered collection of unique elements"),
        ("What does enumerate() do?",
         "Returns index-value pairs from an iterable"),
        ("What is a context manager?",
         "An object used with the with statement"),
        ("What does zip() do?",
         "Combines multiple iterables element-wise"),
        ("What is *args?",
         "Accepts variable number of positional arguments"),
        ("What is **kwargs?",
         "Accepts variable number of keyword arguments"),
        ("What is a virtual environment?",
         "An isolated Python environment for dependencies"),
        ("What does map() do?",
         "Applies a function to every item in an iterable"),
        ("What is the difference between == and is?",
         "== checks value equality, is checks identity"),
        ("What is a docstring?",
         "A string literal documenting a module or function"),
        ("What does filter() do?",
         "Returns elements for which a function returns True"),
        ("What is a class method?",
         "A method bound to the class, not the instance"),
        ("What is list slicing?",
         "Extracting parts of a list using [start:stop]"),
        ("What does sorted() do?",
         "Returns a new sorted list from an iterable"),
        ("What is a frozen set?",
         "An immutable version of a set"),
        ("What does type() return?",
         "The type of an object"),
        ("What is an f-string?",
         "Formatted string literal: f'Hello {name}'"),
        ("What is the GIL?",
         "Global Interpreter Lock — limits thread execution"),
        ("What does any() do?",
         "Returns True if any element is truthy"),
        ("What does all() do?",
         "Returns True if all elements are truthy"),
        ("What is a property decorator?",
         "Defines getter/setter methods as attributes"),
        ("What is an abstract class?",
         "A class that cannot be instantiated directly"),
        ("What does isinstance() do?",
         "Checks if an object is an instance of a class"),
        ("What is a module?",
         "A file containing Python definitions"),
        ("What is a package?",
         "A directory of modules with __init__.py"),
        ("What does the pass statement do?",
         "A null operation — does nothing"),
        ("What is string interpolation?",
         "Embedding expressions inside string literals"),
        ("What is the walrus operator?",
         ":= assigns a value as part of an expression"),
        ("What is a dataclass?",
         "A decorator that auto-generates __init__ etc."),
        ("What is asyncio?",
         "A library for writing async code in Python"),
        ("What does yield do?",
         "Pauses a generator and returns a value"),
        ("What is a classmethod?",
         "A method that receives the class as first arg"),
        ("What is a staticmethod?",
         "A method that does not receive self or cls"),
        ("What is monkey patching?",
         "Modifying classes or modules at runtime"),
        ("What is pickle?",
         "A module for serializing Python objects"),
        ("What is a collections module?",
         "Provides specialized container data types"),
        ("What does vars() return?",
         "The __dict__ attribute of an object"),
        ("What is a descriptor?",
         "An object defining __get__, __set__, or __delete__"),
        ("What is pathlib?",
         "An object-oriented filesystem path library"),
    ],
    "Flask Web Development": [
        ("What decorator makes a route?", "@app.route()"),
        ("How do you run a Flask app?", "flask run"),
        ("What is a Blueprint?",
         "A way to organize routes into modules"),
        ("How do you access form data?",
         "request.form['field_name']"),
        ("What does render_template do?",
         "Renders a Jinja2 HTML template"),
        ("How do you redirect?",
         "Using redirect(url_for('view_name'))"),
        ("What is the session object?",
         "Server-side storage for user data"),
        ("How do you flash a message?",
         "Using flash('message', 'category')"),
        ("What is Jinja2?", "Flask's template engine"),
        ("What does url_for() do?",
         "Generates a URL for a given endpoint"),
        ("How do you set a secret key?",
         "app.secret_key = 'your_key'"),
        ("What is CSRF protection?",
         "Defense against cross-site request forgery"),
        ("How do you serve static files?",
         "Place them in the static/ folder"),
        ("What is g in Flask?",
         "Application context global for request data"),
        ("What method handles POST?",
         "methods=['GET', 'POST'] in route decorator"),
        ("What is a teardown function?",
         "Runs after each request for cleanup"),
        ("How do you return JSON?",
         "Using jsonify({'key': 'value'})"),
        ("What does abort(404) do?",
         "Returns a 404 Not Found response"),
        ("How do you get query parameters?",
         "request.args.get('param')"),
        ("What is the application factory pattern?",
         "Creating the app inside a function"),
        ("What is Werkzeug?",
         "The WSGI toolkit Flask is built on"),
        ("What is a context processor?",
         "Makes variables available to all templates"),
        ("What is a before_request hook?",
         "A function that runs before each request"),
        ("What is an error handler?",
         "A function registered to handle HTTP errors"),
        ("What does make_response() do?",
         "Creates a Response object for customization"),
        ("What is a middleware?",
         "Code that processes requests before the app"),
        ("What is Flask-SQLAlchemy?",
         "An ORM extension for Flask"),
        ("What is a view function?",
         "A function that handles a request and returns a response"),
        ("What is request.method?",
         "The HTTP method of the current request"),
        ("What is the static folder?",
         "Default directory for CSS, JS, and image files"),
        ("What is a macro in Jinja2?",
         "A reusable template snippet like a function"),
        ("What is template inheritance?",
         "Extending a base template with blocks"),
        ("What does send_file() do?",
         "Sends a file from the server to the client"),
        ("What is the test client?",
         "A tool for testing Flask apps without a server"),
        ("What is a cookie in Flask?",
         "Data stored in the client's browser"),
        ("What does request.files contain?",
         "Uploaded files from a multipart form"),
        ("What is a 302 response?",
         "A redirect status code"),
        ("What is WSGI?",
         "Web Server Gateway Interface — Python web standard"),
        ("What is a signal in Flask?",
         "A notification when certain actions occur"),
        ("What does after_request do?",
         "Runs a function after each response is created"),
        ("What is a response object?",
         "The object Flask sends back to the client"),
        ("What is the config object?",
         "Stores app configuration like SECRET_KEY"),
        ("What is a 404 error?",
         "Page not found — resource does not exist"),
        ("What does request.json return?",
         "Parsed JSON data from the request body"),
        ("What is a Flask extension?",
         "A third-party package that adds functionality"),
        ("What is the app context?",
         "Tracks application-level data during a request"),
        ("What is the request context?",
         "Tracks request-level data like URL and method"),
    ],
    "SQL Fundamentals": [
        ("What does SELECT do?", "Retrieves data from a table"),
        ("What does INSERT INTO do?",
         "Adds a new row to a table"),
        ("What is a PRIMARY KEY?",
         "A unique identifier for each row"),
        ("What does WHERE do?", "Filters rows by condition"),
        ("What is a JOIN?",
         "Combines rows from two or more tables"),
        ("What does ORDER BY do?",
         "Sorts the result set"),
        ("What is an INDEX?",
         "A data structure that speeds up queries"),
        ("What does GROUP BY do?",
         "Groups rows that have the same values"),
        ("What is a FOREIGN KEY?",
         "A reference to a primary key in another table"),
        ("What does UPDATE do?",
         "Modifies existing rows in a table"),
        ("What does DELETE do?",
         "Removes rows from a table"),
        ("What is NULL?",
         "Represents missing or unknown data"),
        ("What does LIKE do?",
         "Pattern matching in WHERE clause"),
        ("What is a subquery?",
         "A query nested inside another query"),
        ("What does COUNT() do?",
         "Returns the number of rows"),
        ("What is DISTINCT?",
         "Returns only unique values"),
        ("What does HAVING do?",
         "Filters groups after GROUP BY"),
        ("What is a transaction?",
         "A unit of work that is atomic"),
        ("What does ALTER TABLE do?",
         "Modifies a table structure"),
        ("What is normalization?",
         "Organizing data to reduce redundancy"),
        ("What is a view?",
         "A virtual table based on a SELECT query"),
        ("What does UNION do?",
         "Combines results of two SELECT statements"),
        ("What is a stored procedure?",
         "A saved SQL program that can be called"),
        ("What does BETWEEN do?",
         "Filters values within a range"),
        ("What is a composite key?",
         "A primary key made of multiple columns"),
        ("What does IN do?",
         "Checks if a value is in a list"),
        ("What is referential integrity?",
         "Ensuring foreign keys point to valid rows"),
        ("What does COALESCE do?",
         "Returns the first non-null value"),
        ("What is a trigger?",
         "Code that runs automatically on table events"),
        ("What does CASE do?",
         "Conditional logic inside a query"),
        ("What is a cursor?",
         "An object for iterating over result rows"),
        ("What does TRUNCATE do?",
         "Removes all rows from a table quickly"),
        ("What is an aggregate function?",
         "A function like SUM, AVG, COUNT on groups"),
        ("What is a self-join?",
         "A table joined with itself"),
        ("What does EXISTS do?",
         "Tests if a subquery returns any rows"),
        ("What is a window function?",
         "A function that operates over a set of rows"),
        ("What does ROW_NUMBER() do?",
         "Assigns a sequential number to each row"),
        ("What is a CTE?",
         "Common Table Expression — a named subquery"),
        ("What does EXPLAIN do?",
         "Shows the query execution plan"),
        ("What is a deadlock?",
         "Two transactions waiting for each other"),
        ("What is ACID?",
         "Atomicity, Consistency, Isolation, Durability"),
        ("What does VACUUM do in SQLite?",
         "Rebuilds the database to reclaim space"),
        ("What is a left join?",
         "Returns all rows from left table plus matches"),
        ("What is a cross join?",
         "Returns the Cartesian product of two tables"),
        ("What does OFFSET do?",
         "Skips a number of rows before returning"),
        ("What is a unique constraint?",
         "Ensures all values in a column are distinct"),
        ("What does REPLACE INTO do?",
         "Inserts or replaces if unique constraint fails"),
    ],
    "JavaScript Essentials": [
        ("What is let vs var?",
         "let is block-scoped, var is function-scoped"),
        ("What is === in JS?",
         "Strict equality (no type coercion)"),
        ("What is a callback?",
         "A function passed as an argument"),
        ("What does JSON stand for?",
         "JavaScript Object Notation"),
        ("What is an arrow function?",
         "Shorthand: (x) => x * 2"),
        ("What is the DOM?",
         "Document Object Model — HTML tree API"),
        ("What does typeof return?",
         "A string indicating the type"),
        ("What is a promise?",
         "An object representing an async result"),
        ("What is null vs undefined?",
         "null is intentional absence, undefined is unset"),
        ("What does map() do on arrays?",
         "Transforms each element and returns new array"),
        ("What is NaN?", "Not a Number — invalid math result"),
        ("What is hoisting?",
         "Variables and functions moved to top of scope"),
        ("What does console.log do?",
         "Prints output to the console"),
        ("What is an event listener?",
         "A function that runs on a DOM event"),
        ("What is destructuring?",
         "Extracting values: const {a, b} = obj"),
        ("What is the spread operator?",
         "... expands an iterable into elements"),
        ("What is async/await?",
         "Syntax for writing async code synchronously"),
        ("What is localStorage?",
         "Persistent key-value storage in the browser"),
        ("What does parseInt() do?",
         "Converts a string to an integer"),
        ("What is a closure?",
         "A function that remembers its outer scope"),
        ("What is the event loop?",
         "Handles async operations in a single thread"),
        ("What is a prototype?",
         "An object from which others inherit properties"),
        ("What does Object.keys() do?",
         "Returns an array of an object's property names"),
        ("What is a template literal?",
         "A string with backticks allowing interpolation"),
        ("What is a module in JS?",
         "A file that exports and imports functionality"),
        ("What does fetch() do?",
         "Makes HTTP requests from the browser"),
        ("What is try/catch?",
         "Error handling syntax in JavaScript"),
        ("What is a class in JS?",
         "Syntactic sugar for constructor functions"),
        ("What does Array.filter() do?",
         "Returns elements that pass a test function"),
        ("What is a WeakMap?",
         "A map with weakly held object keys"),
        ("What does reduce() do?",
         "Reduces an array to a single value"),
        ("What is strict mode?",
         "A restricted variant of JavaScript"),
        ("What is a Symbol?",
         "A unique and immutable primitive value"),
        ("What is optional chaining?",
         "?.  safely accesses nested properties"),
        ("What is the nullish coalescing operator?",
         "?? returns right operand if left is null/undefined"),
        ("What does Object.assign() do?",
         "Copies properties from source to target objects"),
        ("What is a generator function?",
         "A function using yield to produce values lazily"),
        ("What is a Proxy in JS?",
         "An object that intercepts operations on another"),
        ("What does Array.find() do?",
         "Returns the first element matching a condition"),
        ("What is a Set in JS?",
         "A collection of unique values"),
        ("What is a Map in JS?",
         "A collection of key-value pairs with any key type"),
        ("What does JSON.stringify() do?",
         "Converts a JavaScript object to a JSON string"),
        ("What is debouncing?",
         "Delaying function execution until input stops"),
        ("What does Array.flat() do?",
         "Flattens nested arrays by one level"),
        ("What is the this keyword?",
         "Refers to the current execution context"),
        ("What is event bubbling?",
         "Events propagate from target up through parents"),
        ("What does Promise.all() do?",
         "Resolves when all promises in an array resolve"),
    ],
    "Data Structures": [
        ("What is an array?",
         "A contiguous block of indexed elements"),
        ("What is a linked list?",
         "Nodes connected by pointers"),
        ("What is a stack?", "LIFO — last in, first out"),
        ("What is a queue?", "FIFO — first in, first out"),
        ("What is a hash table?",
         "Key-value store using a hash function"),
        ("What is a binary tree?",
         "A tree where each node has at most two children"),
        ("What is a graph?",
         "Nodes connected by edges"),
        ("What is O(n) time complexity?",
         "Linear — grows proportionally with input"),
        ("What is O(1)?",
         "Constant time — independent of input size"),
        ("What is a heap?",
         "A tree-based priority queue"),
        ("What is BFS?",
         "Breadth-first search — level by level"),
        ("What is DFS?",
         "Depth-first search — go deep first"),
        ("What is a balanced tree?",
         "A tree where heights differ by at most 1"),
        ("What is a trie?",
         "A tree for storing strings character by character"),
        ("What is recursion?",
         "A function that calls itself"),
        ("What is memoization?",
         "Caching results of expensive function calls"),
        ("What is a set?",
         "A collection of unique elements"),
        ("What is a deque?",
         "A double-ended queue"),
        ("What is amortized analysis?",
         "Average cost per operation over time"),
        ("What is a B-tree?",
         "A self-balancing tree used in databases"),
        ("What is a red-black tree?",
         "A self-balancing BST with color properties"),
        ("What is topological sort?",
         "Ordering vertices in a DAG linearly"),
        ("What is Dijkstra's algorithm?",
         "Finds shortest path in a weighted graph"),
        ("What is a hash collision?",
         "Two keys mapping to the same hash index"),
        ("What is dynamic programming?",
         "Solving problems by breaking into subproblems"),
        ("What is a skip list?",
         "A linked list with express lanes for fast search"),
        ("What is a segment tree?",
         "A tree for range queries on arrays"),
        ("What is an AVL tree?",
         "A self-balancing BST with strict height balance"),
        ("What is a bloom filter?",
         "A space-efficient probabilistic data structure"),
        ("What is a circular buffer?",
         "A fixed-size buffer that wraps around"),
        ("What is a union-find structure?",
         "Tracks elements partitioned into disjoint sets"),
        ("What is a suffix array?",
         "A sorted array of all suffixes of a string"),
        ("What is a Fibonacci heap?",
         "A heap with amortized O(1) insert and decrease-key"),
        ("What is a sparse table?",
         "A structure for static range minimum queries"),
        ("What is a priority queue?",
         "A queue where elements have priorities"),
        ("What is a doubly linked list?",
         "A linked list with prev and next pointers"),
        ("What is a hash map?",
         "An associative array using a hash function"),
        ("What is a binary search?",
         "O(log n) search on a sorted array"),
        ("What is insertion sort?",
         "Builds sorted array one element at a time"),
        ("What is merge sort?",
         "Divide and conquer sort with O(n log n)"),
        ("What is quick sort?",
         "Partition-based sort with average O(n log n)"),
        ("What is bubble sort?",
         "Repeatedly swaps adjacent unsorted elements"),
        ("What is a directed graph?",
         "A graph where edges have direction"),
        ("What is an adjacency list?",
         "Graph representation using lists of neighbors"),
        ("What is Kruskal's algorithm?",
         "Finds minimum spanning tree using edges"),
        ("What is a splay tree?",
         "A BST that moves accessed nodes to root"),
        ("What is counting sort?",
         "Non-comparison sort using element counts"),
    ],
    "World Capitals": [
        ("Capital of France?", "Paris"),
        ("Capital of Japan?", "Tokyo"),
        ("Capital of Brazil?", "Brasilia"),
        ("Capital of Australia?", "Canberra"),
        ("Capital of Canada?", "Ottawa"),
        ("Capital of Germany?", "Berlin"),
        ("Capital of India?", "New Delhi"),
        ("Capital of South Korea?", "Seoul"),
        ("Capital of Mexico?", "Mexico City"),
        ("Capital of Egypt?", "Cairo"),
        ("Capital of Turkey?", "Ankara"),
        ("Capital of Thailand?", "Bangkok"),
        ("Capital of Argentina?", "Buenos Aires"),
        ("Capital of Sweden?", "Stockholm"),
        ("Capital of Finland?", "Helsinki"),
        ("Capital of Norway?", "Oslo"),
        ("Capital of Poland?", "Warsaw"),
        ("Capital of Portugal?", "Lisbon"),
        ("Capital of Switzerland?", "Bern"),
        ("Capital of South Africa?", "Pretoria"),
        ("Capital of Morocco?", "Rabat"),
        ("Capital of Peru?", "Lima"),
        ("Capital of Chile?", "Santiago"),
        ("Capital of Colombia?", "Bogota"),
        ("Capital of Nigeria?", "Abuja"),
        ("Capital of Kenya?", "Nairobi"),
        ("Capital of Vietnam?", "Hanoi"),
        ("Capital of Philippines?", "Manila"),
        ("Capital of Indonesia?", "Jakarta"),
        ("Capital of Malaysia?", "Kuala Lumpur"),
        ("Capital of Ireland?", "Dublin"),
        ("Capital of Iceland?", "Reykjavik"),
        ("Capital of New Zealand?", "Wellington"),
        ("Capital of Cuba?", "Havana"),
        ("Capital of Greece?", "Athens"),
        ("Capital of Czech Republic?", "Prague"),
        ("Capital of Hungary?", "Budapest"),
        ("Capital of Ukraine?", "Kyiv"),
        ("Capital of Romania?", "Bucharest"),
        ("Capital of Croatia?", "Zagreb"),
        ("Capital of Austria?", "Vienna"),
        ("Capital of Belgium?", "Brussels"),
        ("Capital of Denmark?", "Copenhagen"),
        ("Capital of Iran?", "Tehran"),
        ("Capital of Iraq?", "Baghdad"),
        ("Capital of Pakistan?", "Islamabad"),
        ("Capital of Ethiopia?", "Addis Ababa"),
        ("Capital of Tanzania?", "Dodoma"),
        ("Capital of Venezuela?", "Caracas"),
        ("Capital of Bolivia?", "Sucre"),
        ("Capital of Paraguay?", "Asuncion"),
        ("Capital of Uruguay?", "Montevideo"),
        ("Capital of Ecuador?", "Quito"),
        ("Capital of Jamaica?", "Kingston"),
        ("Capital of Nepal?", "Kathmandu"),
        ("Capital of Sri Lanka?", "Colombo"),
        ("Capital of Bangladesh?", "Dhaka"),
        ("Capital of Myanmar?", "Naypyidaw"),
        ("Capital of Cambodia?", "Phnom Penh"),
    ],
    "Spanish Vocabulary": [
        ("Hello", "Hola"),
        ("Goodbye", "Adios"),
        ("Please", "Por favor"),
        ("Thank you", "Gracias"),
        ("Water", "Agua"),
        ("Food", "Comida"),
        ("House", "Casa"),
        ("Book", "Libro"),
        ("Cat", "Gato"),
        ("Dog", "Perro"),
        ("Friend", "Amigo"),
        ("Family", "Familia"),
        ("School", "Escuela"),
        ("Time", "Tiempo"),
        ("Money", "Dinero"),
        ("Work", "Trabajo"),
        ("Love", "Amor"),
        ("Good morning", "Buenos dias"),
        ("Good night", "Buenas noches"),
        ("How are you?", "Como estas?"),
        ("I don't understand",
         "No entiendo"),
        ("Where is...?", "Donde esta...?"),
        ("How much does it cost?",
         "Cuanto cuesta?"),
        ("Yes", "Si"),
        ("No", "No"),
        ("Big", "Grande"),
        ("Small", "Pequeno"),
        ("Hot", "Caliente"),
        ("Cold", "Frio"),
        ("Beautiful", "Hermoso"),
        ("Happy", "Feliz"),
        ("Sad", "Triste"),
        ("Fast", "Rapido"),
        ("Slow", "Lento"),
        ("To eat", "Comer"),
        ("To drink", "Beber"),
        ("To run", "Correr"),
        ("To sleep", "Dormir"),
        ("To speak", "Hablar"),
        ("To write", "Escribir"),
        ("To read", "Leer"),
        ("To think", "Pensar"),
        ("To know", "Saber"),
        ("Red", "Rojo"),
        ("Blue", "Azul"),
        ("Green", "Verde"),
        ("White", "Blanco"),
        ("Black", "Negro"),
        ("Monday", "Lunes"),
        ("Tuesday", "Martes"),
        ("Wednesday", "Miercoles"),
        ("Thursday", "Jueves"),
        ("Friday", "Viernes"),
        ("Saturday", "Sabado"),
        ("Sunday", "Domingo"),
    ],
    "Biology 101": [
        ("What is a cell?",
         "The basic unit of life"),
        ("What is DNA?",
         "Deoxyribonucleic acid — carries genetic info"),
        ("What is mitosis?",
         "Cell division producing two identical cells"),
        ("What is photosynthesis?",
         "Plants converting light to energy"),
        ("What is an enzyme?",
         "A protein that catalyzes reactions"),
        ("What is ATP?",
         "Adenosine triphosphate — energy currency"),
        ("What are ribosomes?",
         "Organelles that synthesize proteins"),
        ("What is evolution?",
         "Change in species over generations"),
        ("What is an ecosystem?",
         "A community of organisms and their environment"),
        ("What is meiosis?",
         "Cell division producing four gametes"),
        ("What is a gene?",
         "A segment of DNA encoding a trait"),
        ("What is a mutation?",
         "A change in the DNA sequence"),
        ("What is homeostasis?",
         "Maintaining stable internal conditions"),
        ("What is the cell membrane?",
         "A lipid bilayer surrounding the cell"),
        ("What is osmosis?",
         "Water movement through a semipermeable membrane"),
        ("What are chromosomes?",
         "Structures of coiled DNA and proteins"),
        ("What is natural selection?",
         "Survival of the fittest organisms"),
        ("What is a virus?",
         "A non-living particle that infects cells"),
        ("What is the nucleus?",
         "The control center of a cell"),
        ("What is respiration?",
         "Converting glucose to ATP using oxygen"),
        ("What is a prokaryote?",
         "An organism without a membrane-bound nucleus"),
        ("What is a eukaryote?",
         "An organism with a membrane-bound nucleus"),
        ("What is a protein?",
         "A chain of amino acids with specific functions"),
        ("What is a lipid?",
         "A fat-soluble molecule used for energy storage"),
        ("What is a carbohydrate?",
         "A sugar molecule used for energy"),
        ("What is the mitochondria?",
         "The powerhouse of the cell"),
        ("What is a vacuole?",
         "A storage organelle in plant cells"),
        ("What is chloroplast?",
         "The organelle where photosynthesis occurs"),
        ("What is a food chain?",
         "A linear sequence of organisms eating each other"),
        ("What is biodiversity?",
         "The variety of life in an ecosystem"),
        ("What is an allele?",
         "A variant form of a gene"),
        ("What is a phenotype?",
         "The observable traits of an organism"),
        ("What is a genotype?",
         "The genetic makeup of an organism"),
        ("What is symbiosis?",
         "A close relationship between two species"),
        ("What is a biome?",
         "A large community of flora and fauna"),
        ("What is taxonomy?",
         "The science of classifying organisms"),
        ("What is RNA?",
         "Ribonucleic acid — helps build proteins"),
        ("What is a stem cell?",
         "An undifferentiated cell that can specialize"),
        ("What is fermentation?",
         "Anaerobic energy production in cells"),
        ("What is the Krebs cycle?",
         "A cycle producing ATP in mitochondria"),
        ("What is ecology?",
         "The study of organisms and their environment"),
        ("What is an antibiotic?",
         "A substance that kills or inhibits bacteria"),
        ("What is a dominant trait?",
         "A trait that appears when one allele is present"),
        ("What is a recessive trait?",
         "A trait that requires two copies of the allele"),
        ("What is genetic drift?",
         "Random changes in allele frequency"),
        ("What is a hormone?",
         "A chemical messenger in the body"),
        ("What is the nervous system?",
         "A network of neurons that coordinate actions"),
    ],
    "Chemistry Basics": [
        ("What is an atom?",
         "The smallest unit of an element"),
        ("What is a molecule?",
         "Two or more atoms bonded together"),
        ("What is the periodic table?",
         "An arrangement of elements by atomic number"),
        ("What is pH?",
         "A scale measuring acidity or basicity"),
        ("What is an ion?",
         "An atom with a net electric charge"),
        ("What is a covalent bond?",
         "Atoms sharing electron pairs"),
        ("What is an ionic bond?",
         "Bond formed by electron transfer"),
        ("What is Avogadro's number?",
         "6.022 x 10^23 — particles per mole"),
        ("What is a catalyst?",
         "A substance that speeds up a reaction"),
        ("What is oxidation?",
         "Loss of electrons in a reaction"),
        ("What is reduction?",
         "Gain of electrons in a reaction"),
        ("What is a mole?",
         "A unit for amount of substance"),
        ("What is an acid?",
         "A substance that donates H+ ions"),
        ("What is a base?",
         "A substance that accepts H+ ions"),
        ("What is a solution?",
         "A homogeneous mixture of substances"),
        ("What is valence?",
         "The combining capacity of an element"),
        ("What is an isotope?",
         "Atoms of same element with different neutrons"),
        ("What is electronegativity?",
         "An atom's ability to attract electrons"),
        ("What is a chemical equation?",
         "A symbolic representation of a reaction"),
        ("What is enthalpy?",
         "Heat content of a system at constant pressure"),
        ("What is a polymer?",
         "A large molecule made of repeating units"),
        ("What is an electrolyte?",
         "A substance that conducts electricity in solution"),
        ("What is a precipitate?",
         "A solid formed from a solution reaction"),
        ("What is molarity?",
         "Moles of solute per liter of solution"),
        ("What is an alloy?",
         "A mixture of metals"),
        ("What is sublimation?",
         "Direct transition from solid to gas"),
        ("What is a Lewis structure?",
         "A diagram showing electron pairs in molecules"),
        ("What is Boyle's law?",
         "Pressure and volume are inversely proportional"),
        ("What is a redox reaction?",
         "A reaction involving electron transfer"),
        ("What is the ideal gas law?",
         "PV = nRT"),
        ("What is an exothermic reaction?",
         "A reaction that releases heat"),
        ("What is an endothermic reaction?",
         "A reaction that absorbs heat"),
        ("What is a buffer solution?",
         "A solution that resists pH changes"),
        ("What is Le Chatelier's principle?",
         "A system shifts to counteract changes"),
        ("What is a half-life?",
         "Time for half of a substance to decay"),
        ("What is stoichiometry?",
         "Calculating quantities in chemical reactions"),
        ("What is a noble gas?",
         "An element with a full outer electron shell"),
        ("What is an organic compound?",
         "A compound containing carbon atoms"),
        ("What is Charles's law?",
         "Volume is proportional to temperature"),
        ("What is an electron cloud?",
         "The region where electrons are likely found"),
        ("What is a chemical bond?",
         "A force holding atoms together"),
        ("What is mass number?",
         "Total protons and neutrons in an atom"),
        ("What is a solvent?",
         "The substance that dissolves a solute"),
        ("What is crystallization?",
         "Forming solid crystals from a solution"),
        ("What is a combustion reaction?",
         "A substance reacting with oxygen producing heat"),
        ("What is an oxidation number?",
         "The charge an atom would have if ionic"),
        ("What is a phase diagram?",
         "A chart showing states of matter vs temperature"),
    ],
    "History Dates": [
        ("When did WW1 start?", "1914"),
        ("When did WW2 end?", "1945"),
        ("When was the Moon landing?", "1969"),
        ("When did the French Revolution begin?", "1789"),
        ("When was the Declaration of Independence?", "1776"),
        ("When did the Roman Empire fall?", "476 AD"),
        ("When was the printing press invented?",
         "Around 1440 by Gutenberg"),
        ("When did Columbus reach the Americas?", "1492"),
        ("When did the Berlin Wall fall?", "1989"),
        ("When was the Renaissance period?",
         "14th to 17th century"),
        ("When was the Russian Revolution?", "1917"),
        ("When did the Cold War end?", "1991"),
        ("When was the Magna Carta signed?", "1215"),
        ("When did the Industrial Revolution begin?",
         "Around 1760"),
        ("When was the UN founded?", "1945"),
        ("When did WW2 start?", "1939"),
        ("When was the Civil Rights Act?", "1964"),
        ("When was the first computer built?",
         "1945 — ENIAC"),
        ("When did the internet go public?",
         "1991 — World Wide Web"),
        ("When was the EU founded?",
         "1993 (Maastricht Treaty)"),
        ("When was the Reformation?",
         "1517 — Luther's 95 Theses"),
        ("When was the Battle of Waterloo?", "1815"),
        ("When did the Ottoman Empire end?", "1922"),
        ("When was the Treaty of Versailles?", "1919"),
        ("When did slavery end in the US?",
         "1865 — 13th Amendment"),
        ("When was the Korean War?", "1950-1953"),
        ("When was the Vietnam War?", "1955-1975"),
        ("When was the atomic bomb dropped?",
         "August 1945 — Hiroshima and Nagasaki"),
        ("When did India gain independence?", "1947"),
        ("When was the Suez Crisis?", "1956"),
        ("When was NATO founded?", "1949"),
        ("When did China's Cultural Revolution begin?", "1966"),
        ("When was the Chernobyl disaster?", "1986"),
        ("When was the Spanish Civil War?", "1936-1939"),
        ("When was the Cuban Missile Crisis?", "1962"),
        ("When did apartheid end in South Africa?", "1994"),
        ("When was the Titanic sinking?", "1912"),
        ("When was the Great Depression?",
         "1929-1939"),
        ("When did the Roman Republic begin?",
         "509 BC"),
        ("When was the Battle of Hastings?", "1066"),
        ("When was the Louisiana Purchase?", "1803"),
        ("When did the Meiji Restoration begin?", "1868"),
        ("When was the Panama Canal opened?", "1914"),
        ("When was the Space Shuttle Challenger disaster?",
         "1986"),
        ("When did the Soviet Union form?", "1922"),
        ("When was the Bolshevik Revolution?",
         "October 1917"),
        ("When was the Marshall Plan?", "1948"),
    ],
}

DIFFICULTIES = ["easy", "medium", "hard"]


def seed():
    db = sqlite3.connect(DB_PATH)
    db.execute("PRAGMA foreign_keys = ON")

    # Clear existing data
    db.execute("DELETE FROM session_cards")
    db.execute("DELETE FROM session_answers")
    db.execute("DELETE FROM study_sessions")
    db.execute("DELETE FROM flashcards")
    db.execute("DELETE FROM projects")
    db.execute("DELETE FROM users")
    db.commit()

    random.seed(42)

    # Create users
    user_ids = {}
    for username, password in USERS:
        cursor = db.execute(
            "INSERT INTO users (username, password) VALUES (?, ?)",
            (username,
             generate_password_hash(password, method="pbkdf2:sha256")),
        )
        user_ids[username] = cursor.lastrowid
    db.commit()

    # Create projects and flashcards
    project_ids = {}
    total_cards = 0
    for user_idx, project_name, is_public in PROJECTS:
        user_id = list(user_ids.values())[user_idx - 1]
        cursor = db.execute(
            "INSERT INTO projects (user_id, name, is_public) "
            "VALUES (?, ?, ?)",
            (user_id, project_name, is_public),
        )
        project_id = cursor.lastrowid
        project_ids[project_name] = project_id

        cards = CARD_SETS[project_name]
        for front, back in cards:
            difficulty = random.choice(DIFFICULTIES)
            db.execute(
                "INSERT INTO flashcards "
                "(project_id, front, back, difficulty) "
                "VALUES (?, ?, ?, ?)",
                (project_id, front, back, difficulty),
            )
            total_cards += 1
    db.commit()

    # Create study sessions
    session_count = 0
    for project_user_idx, project_name, _ in PROJECTS:
        user_id = list(user_ids.values())[project_user_idx - 1]
        project_id = project_ids[project_name]

        card_rows = db.execute(
            "SELECT id FROM flashcards WHERE project_id = ?",
            (project_id,),
        ).fetchall()
        card_ids = [r[0] for r in card_rows]

        num_sessions = random.randint(1, 4)
        for _ in range(num_sessions):
            num_cards = len(card_ids)
            correct = random.randint(
                num_cards // 3, num_cards
            )
            cursor = db.execute(
                "INSERT INTO study_sessions "
                "(user_id, project_id, total_cards, "
                "correct, completed) "
                "VALUES (?, ?, ?, ?, 1)",
                (user_id, project_id, num_cards, correct),
            )
            session_id = cursor.lastrowid

            shuffled = list(card_ids)
            random.shuffle(shuffled)
            known_ids = set(shuffled[:correct])

            for card_id in card_ids:
                known = 1 if card_id in known_ids else 0
                db.execute(
                    "INSERT INTO session_answers "
                    "(session_id, card_id, known) "
                    "VALUES (?, ?, ?)",
                    (session_id, card_id, known),
                )
            session_count += 1
    db.commit()
    db.close()

    print(f"Seeded: {len(USERS)} users, {len(PROJECTS)} projects, "
          f"{total_cards} flashcards, {session_count} sessions")


if __name__ == "__main__":
    seed()
